"""autogenerated by genpy from ethercat_hardware/MotorTemperature.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class MotorTemperature(genpy.Message):
  _md5sum = "d8c7239cd096d6f25b75bff6b63f2162"
  _type = "ethercat_hardware/MotorTemperature"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Sample of motor heating information
time    stamp
float64 winding_temperature
float64 housing_temperature
float64 ambient_temperature
float64 heating_power
"""
  __slots__ = ['stamp','winding_temperature','housing_temperature','ambient_temperature','heating_power']
  _slot_types = ['time','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,winding_temperature,housing_temperature,ambient_temperature,heating_power

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorTemperature, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.winding_temperature is None:
        self.winding_temperature = 0.
      if self.housing_temperature is None:
        self.housing_temperature = 0.
      if self.ambient_temperature is None:
        self.ambient_temperature = 0.
      if self.heating_power is None:
        self.heating_power = 0.
    else:
      self.stamp = genpy.Time()
      self.winding_temperature = 0.
      self.housing_temperature = 0.
      self.ambient_temperature = 0.
      self.heating_power = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2I4d.pack(_x.stamp.secs, _x.stamp.nsecs, _x.winding_temperature, _x.housing_temperature, _x.ambient_temperature, _x.heating_power))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.stamp.secs, _x.stamp.nsecs, _x.winding_temperature, _x.housing_temperature, _x.ambient_temperature, _x.heating_power,) = _struct_2I4d.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2I4d.pack(_x.stamp.secs, _x.stamp.nsecs, _x.winding_temperature, _x.housing_temperature, _x.ambient_temperature, _x.heating_power))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.stamp.secs, _x.stamp.nsecs, _x.winding_temperature, _x.housing_temperature, _x.ambient_temperature, _x.heating_power,) = _struct_2I4d.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2I4d = struct.Struct("<2I4d")
