"""autogenerated by genpy from ethercat_hardware/MotorTraceSample.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MotorTraceSample(genpy.Message):
  _md5sum = "3734a66334bc2033448f9c561d39c5e0"
  _type = "ethercat_hardware/MotorTraceSample"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 timestamp
bool    enabled
float64 supply_voltage
float64 measured_motor_voltage
float64 programmed_pwm
float64 executed_current
float64 measured_current
float64 velocity
float64 encoder_position
uint32  encoder_error_count
float64 motor_voltage_error_limit
float64 filtered_motor_voltage_error
float64 filtered_abs_motor_voltage_error
float64 filtered_measured_voltage_error
float64 filtered_abs_measured_voltage_error
float64 filtered_current_error
float64 filtered_abs_current_error
"""
  __slots__ = ['timestamp','enabled','supply_voltage','measured_motor_voltage','programmed_pwm','executed_current','measured_current','velocity','encoder_position','encoder_error_count','motor_voltage_error_limit','filtered_motor_voltage_error','filtered_abs_motor_voltage_error','filtered_measured_voltage_error','filtered_abs_measured_voltage_error','filtered_current_error','filtered_abs_current_error']
  _slot_types = ['float64','bool','float64','float64','float64','float64','float64','float64','float64','uint32','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,enabled,supply_voltage,measured_motor_voltage,programmed_pwm,executed_current,measured_current,velocity,encoder_position,encoder_error_count,motor_voltage_error_limit,filtered_motor_voltage_error,filtered_abs_motor_voltage_error,filtered_measured_voltage_error,filtered_abs_measured_voltage_error,filtered_current_error,filtered_abs_current_error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorTraceSample, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.enabled is None:
        self.enabled = False
      if self.supply_voltage is None:
        self.supply_voltage = 0.
      if self.measured_motor_voltage is None:
        self.measured_motor_voltage = 0.
      if self.programmed_pwm is None:
        self.programmed_pwm = 0.
      if self.executed_current is None:
        self.executed_current = 0.
      if self.measured_current is None:
        self.measured_current = 0.
      if self.velocity is None:
        self.velocity = 0.
      if self.encoder_position is None:
        self.encoder_position = 0.
      if self.encoder_error_count is None:
        self.encoder_error_count = 0
      if self.motor_voltage_error_limit is None:
        self.motor_voltage_error_limit = 0.
      if self.filtered_motor_voltage_error is None:
        self.filtered_motor_voltage_error = 0.
      if self.filtered_abs_motor_voltage_error is None:
        self.filtered_abs_motor_voltage_error = 0.
      if self.filtered_measured_voltage_error is None:
        self.filtered_measured_voltage_error = 0.
      if self.filtered_abs_measured_voltage_error is None:
        self.filtered_abs_measured_voltage_error = 0.
      if self.filtered_current_error is None:
        self.filtered_current_error = 0.
      if self.filtered_abs_current_error is None:
        self.filtered_abs_current_error = 0.
    else:
      self.timestamp = 0.
      self.enabled = False
      self.supply_voltage = 0.
      self.measured_motor_voltage = 0.
      self.programmed_pwm = 0.
      self.executed_current = 0.
      self.measured_current = 0.
      self.velocity = 0.
      self.encoder_position = 0.
      self.encoder_error_count = 0
      self.motor_voltage_error_limit = 0.
      self.filtered_motor_voltage_error = 0.
      self.filtered_abs_motor_voltage_error = 0.
      self.filtered_measured_voltage_error = 0.
      self.filtered_abs_measured_voltage_error = 0.
      self.filtered_current_error = 0.
      self.filtered_abs_current_error = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_dB7dI7d.pack(_x.timestamp, _x.enabled, _x.supply_voltage, _x.measured_motor_voltage, _x.programmed_pwm, _x.executed_current, _x.measured_current, _x.velocity, _x.encoder_position, _x.encoder_error_count, _x.motor_voltage_error_limit, _x.filtered_motor_voltage_error, _x.filtered_abs_motor_voltage_error, _x.filtered_measured_voltage_error, _x.filtered_abs_measured_voltage_error, _x.filtered_current_error, _x.filtered_abs_current_error))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 125
      (_x.timestamp, _x.enabled, _x.supply_voltage, _x.measured_motor_voltage, _x.programmed_pwm, _x.executed_current, _x.measured_current, _x.velocity, _x.encoder_position, _x.encoder_error_count, _x.motor_voltage_error_limit, _x.filtered_motor_voltage_error, _x.filtered_abs_motor_voltage_error, _x.filtered_measured_voltage_error, _x.filtered_abs_measured_voltage_error, _x.filtered_current_error, _x.filtered_abs_current_error,) = _struct_dB7dI7d.unpack(str[start:end])
      self.enabled = bool(self.enabled)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_dB7dI7d.pack(_x.timestamp, _x.enabled, _x.supply_voltage, _x.measured_motor_voltage, _x.programmed_pwm, _x.executed_current, _x.measured_current, _x.velocity, _x.encoder_position, _x.encoder_error_count, _x.motor_voltage_error_limit, _x.filtered_motor_voltage_error, _x.filtered_abs_motor_voltage_error, _x.filtered_measured_voltage_error, _x.filtered_abs_measured_voltage_error, _x.filtered_current_error, _x.filtered_abs_current_error))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 125
      (_x.timestamp, _x.enabled, _x.supply_voltage, _x.measured_motor_voltage, _x.programmed_pwm, _x.executed_current, _x.measured_current, _x.velocity, _x.encoder_position, _x.encoder_error_count, _x.motor_voltage_error_limit, _x.filtered_motor_voltage_error, _x.filtered_abs_motor_voltage_error, _x.filtered_measured_voltage_error, _x.filtered_abs_measured_voltage_error, _x.filtered_current_error, _x.filtered_abs_current_error,) = _struct_dB7dI7d.unpack(str[start:end])
      self.enabled = bool(self.enabled)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_dB7dI7d = struct.Struct("<dB7dI7d")
