(cl:defpackage ethercat_hardware-srv
  (:use )
  (:export
   "SOFTPROCESSORFIRMWAREWRITE"
   "<SOFTPROCESSORFIRMWAREWRITE-REQUEST>"
   "SOFTPROCESSORFIRMWAREWRITE-REQUEST"
   "<SOFTPROCESSORFIRMWAREWRITE-RESPONSE>"
   "SOFTPROCESSORFIRMWAREWRITE-RESPONSE"
   "SOFTPROCESSORRESET"
   "<SOFTPROCESSORRESET-REQUEST>"
   "SOFTPROCESSORRESET-REQUEST"
   "<SOFTPROCESSORRESET-RESPONSE>"
   "SOFTPROCESSORRESET-RESPONSE"
   "SOFTPROCESSORFIRMWAREREAD"
   "<SOFTPROCESSORFIRMWAREREAD-REQUEST>"
   "SOFTPROCESSORFIRMWAREREAD-REQUEST"
   "<SOFTPROCESSORFIRMWAREREAD-RESPONSE>"
   "SOFTPROCESSORFIRMWAREREAD-RESPONSE"
  ))

